// Everything NEXUS can do, for Settings → Funciones: what each feature is, how to use it and
// (when it makes sense) a switch to turn it off. "feature" switches live in settings.disabled
// (main/features.ts removes their tools and hotkeys); "setting" switches are existing settings.
import { ICON } from './constants';

const off = (S, id) => (S.disabled || []).includes(id);
// a switch kept in settings.disabled
const feature = id => ({ on: S => !off(S, id), flip: app => app.toggleFeature(id) });
// a switch that is an existing setting
const setting = (on, flip) => ({ on, flip });

const I = {
  ...ICON,
  wake: 'M12 3a3 3 0 0 0-3 3v6a3 3 0 0 0 6 0V6a3 3 0 0 0-3-3zM5 11a7 7 0 0 0 14 0M12 18v3M3 8l2 1M21 8l-2 1',
  bar: 'M3 6h18v5H3zM6 8.5h8M3 15h12M3 19h8',
  selection: 'M4 5h10M4 9h16M4 13h7M4 19h16M14 11l6 6-3 1-1 3z',
  dictation: 'M12 3a3 3 0 0 0-3 3v5a3 3 0 0 0 6 0V6a3 3 0 0 0-3-3zM5 10a7 7 0 0 0 14 0M8 21h8M12 17v4',
  brain: 'M12 4a4 4 0 0 0-4 4 3.5 3.5 0 0 0-2 6.5A3.5 3.5 0 0 0 9.5 20h1V4.5M12 4a4 4 0 0 1 4 4 3.5 3.5 0 0 1 2 6.5 3.5 3.5 0 0 1-3.5 5.5h-1',
  apps: 'M4 4h7v7H4zM13 4h7v7h-7zM4 13h7v7H4zM15 15h3M16.5 13.5v3',
  folder: 'M3 6h6l2 2h10v11H3z',
  edit: 'M4 20h4L19 9l-4-4L4 16zM13 7l4 4',
  terminal: 'M4 5h16v14H4zM7 9l3 3-3 3M12 15h5',
  power: 'M12 3v8M7 6a7 7 0 1 0 10 0',
  clipboard: 'M8 4h8v3H8zM6 5H5v16h14V5h-1M9 12h6M9 16h4',
  eye: 'M2 12s3.6-7 10-7 10 7 10 7-3.6 7-10 7S2 12 2 12zM12 9a3 3 0 1 0 0 6a3 3 0 1 0 0-6',
  bell: 'M6 16V11a6 6 0 0 1 12 0v5l2 2H4zM10 21h4',
  calendar: 'M4 6h16v14H4zM4 10h16M8 3v4M16 3v4',
  sun: 'M12 8a4 4 0 1 0 0 8a4 4 0 1 0 0-8M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1.5 1.5M17.5 17.5L19 19M5 19l1.5-1.5M17.5 6.5L19 5',
  moon: 'M20 14A8 8 0 1 1 10 4a6 6 0 0 0 10 10z',
  spark: 'M12 3l1.8 4.6L18.5 9l-4.7 1.6L12 15l-1.8-4.4L5.5 9l4.7-1.4z',
  target: 'M12 3a9 9 0 1 0 0 18a9 9 0 1 0 0-18M12 8a4 4 0 1 0 0 8a4 4 0 1 0 0-8M12 11.5v1',
  globe: 'M12 3a9 9 0 1 0 0 18a9 9 0 1 0 0-18M3 12h18M12 3c3 3.5 3 14.5 0 18M12 3c-3 3.5-3 14.5 0 18',
  search: 'M10 4a6 6 0 1 0 0 12a6 6 0 1 0 0-12M20 20l-5.5-5.5',
  slides: 'M3 5h18v11H3zM12 16v4M8 20h8M7 9h6M7 12h4',
  game: 'M6 9h12a3 3 0 0 1 3 3v2a3 3 0 0 1-5.4 1.8L14 14h-4l-1.6 1.8A3 3 0 0 1 3 14v-2a3 3 0 0 1 3-3zM8 11v3M6.5 12.5h3M16 11.5h.01M18 13h.01',
  undo: 'M9 14L4 9l5-5M4 9h10a6 6 0 0 1 0 12h-3',
  wallpaper: 'M3 5h18v12H3zM8 21h8M12 17v4M7 13l3-3 3 3 2-2 3 3',
};

export const FEATURE_GROUPS = [
  {
    name: 'Hablar con NEXUS',
    items: [
      { id: 'voice', icon: I.voice, name: 'Voz y chat', short: 'Háblame o escríbeme', always: true,
        long: 'Me hablas con el micrófono (toca el núcleo o pulsa Ctrl + Alt + Espacio) o me escribes en el chat. Te contesto con voz y por escrito, y sigo el hilo de la conversación.',
        examples: ['¿Qué tiempo hace mañana?', 'Explícame qué es un SSD'] },
      { id: 'wake', icon: I.wake, name: 'Frase de activación', short: 'Me despierto al oír tu frase', ...setting(S => !!S.wakeListen, (app, S) => app.setWakeListen(!S.wakeListen)),
        long: 'Me quedo escuchando solo tu frase («Oye Jarvis», «Hey Nexus»…) y me despierto al oírla, sin tocar nada. El reconocimiento va en tu PC: no se graba ni se envía nada. La frase se cambia en Voz y personalidad.',
        examples: ['Oye Jarvis, ¿qué hora es?'], more: ['voice', 'Voz y audio'] },
      { id: 'bar', icon: I.bar, name: 'Barra flotante', short: 'Pregunta desde cualquier app (Ctrl + Alt + A)', ...feature('bar'),
        long: 'Una barra pequeña que se abre encima de lo que estés haciendo, incluso jugando, para preguntarme algo por escrito sin abrir NEXUS. La respuesta se puede copiar. Esc la cierra.',
        examples: ['Ctrl + Alt + A → «¿cuánto es 15 % de 240?»'] },
      { id: 'selection', icon: I.selection, name: 'Texto seleccionado', short: 'Resumir, traducir o corregir lo que selecciones (Ctrl + Alt + S)', ...feature('selection'),
        long: 'Selecciona un texto en cualquier app (un correo, una web, un documento) y pulsa Ctrl + Alt + S. Te ofrezco resumirlo, traducirlo, corregirlo, explicarlo o responderlo, y con «Pegar en su sitio» lo sustituyo donde estaba.',
        examples: ['Selecciona un párrafo en inglés → Traducir'] },
      { id: 'dictation', icon: I.dictation, name: 'Dictado', short: 'Hablas y se escribe donde esté el cursor (Ctrl + Alt + D)', ...feature('dictation'),
        long: 'En cualquier app (Word, WhatsApp, el navegador…) pulsa Ctrl + Alt + D y habla: el texto se escribe donde tengas el cursor. Para con una pausa o pulsando el atajo otra vez.',
        examples: ['Ctrl + Alt + D en WhatsApp Web y dicta el mensaje'] },
      { id: 'memory', icon: I.brain, name: 'Memoria', short: 'Recuerdo lo que me cuentas de ti', ...setting(S => S.learn !== false, app => app.flip('learn', 'memoryLearn')),
        long: 'Aprendo datos tuyos de lo que hablamos (gustos, personas, lugares, trabajo) y los uso después. Lo ves, editas o borras en el panel Memoria. Si la apagas, solo guardo lo que me pidas recordar expresamente. Todo va cifrado en tu PC.',
        examples: ['Recuerda que mi hermana se llama Laura', '¿Qué te conté de mis vacaciones?'] },
    ],
  },
  {
    name: 'Tu PC',
    items: [
      { id: 'apps', icon: I.apps, name: 'Abrir apps y webs', short: 'Abro programas y páginas', ...feature('apps'),
        long: 'Abro cualquier programa instalado y cualquier web. Las órdenes sencillas («abre Discord») van al momento y sin gastar cupo de la IA.',
        examples: ['Abre Discord', 'Abre YouTube'] },
      { id: 'music', icon: I.music, name: 'Música y Spotify', short: 'Controlo la música y tus listas', ...feature('music'),
        long: 'Pausar, siguiente, volumen y qué suena, desde la app de Spotify. Con tu cuenta conectada (Ajustes → Cuentas) pongo tus listas por su nombre. El panel Música muestra la carátula y la letra.',
        examples: ['Pon mi lista Gym', 'Siguiente canción', 'Sube el volumen'] },
      { id: 'games', icon: I.game, name: 'Juegos de Steam', short: 'Abro, instalo y actualizo tus juegos', ...feature('games'),
        long: 'Leo tus bibliotecas de Steam (en cualquier disco): abro juegos, los instalo, compruebo actualizaciones o te digo cuáles tienes.',
        examples: ['Abre Elden Ring', '¿Qué juegos tengo?'] },
      { id: 'files', icon: I.folder, name: 'Ver tus archivos', short: 'Busco, leo y analizo archivos', ...setting(S => !!(S.agent || {}).files, app => app.setAgent('files', 'agentFiles')),
        long: 'Busco archivos y carpetas, leo documentos y te digo qué ocupa espacio. También me puedes arrastrar archivos al chat. Las claves y contraseñas guardadas en archivos nunca se leen.',
        examples: ['Busca el PDF de la factura de la luz', '¿Qué ocupa tanto en Descargas?'] },
      { id: 'write', icon: I.edit, name: 'Modificar archivos', short: 'Creo, edito y muevo (con tu permiso)', ...setting(S => !!(S.agent || {}).write, app => app.setAgent('write', 'agentWrite')),
        long: 'Guardo, edito, muevo o envío a la papelera archivos, siempre pidiéndote permiso antes. Guardo una copia de lo que cambio durante 7 días para poder deshacerlo.',
        examples: ['Crea una nota en el escritorio con la lista de la compra', 'Deshaz lo último'] },
      { id: 'shell', icon: I.terminal, name: 'Comandos de PowerShell', short: 'Tareas avanzadas (siempre pregunto)', ...setting(S => !!(S.agent || {}).shell, app => app.setAgent('shell', 'agentShell')),
        long: 'Para tareas que no cubren mis otras herramientas ejecuto comandos de PowerShell, mostrándote siempre el comando y pidiéndote permiso cada vez. Apágalo si no lo necesitas.',
        examples: ['¿Qué versión de Windows tengo?'] },
      { id: 'pc', icon: I.power, name: 'Control del PC', short: 'Bloquear, suspender, apagar, brillo', ...feature('pc'),
        long: 'Bloqueo el equipo, apago la pantalla, suspendo, apago o reinicio en X minutos (estos tres te los confirmo) y cambio el brillo en portátiles. Solo lo hago si lo pides tú con tus palabras.',
        examples: ['Bloquea el PC', 'Apaga el ordenador en 30 minutos'] },
      { id: 'clipboard', icon: I.clipboard, name: 'Portapapeles', short: 'Trabajo con lo que has copiado', ...feature('clipboard'),
        long: 'Leo lo que has copiado (texto o imagen) para traducirlo, resumirlo o corregirlo, y te dejo el resultado copiado para pegarlo.',
        examples: ['Traduce lo que he copiado'] },
      { id: 'vision', icon: I.eye, name: 'Ver pantalla e imágenes', short: 'Miro tu pantalla, la cámara o una foto', ...feature('vision'),
        long: 'Solo cuando me lo pides: hago una captura de tu pantalla, una foto con la webcam (con permiso) o miro una imagen, y te explico lo que veo. Siempre te enseño lo que he mirado.',
        examples: ['¿Qué pone en este error?', 'Mira la pantalla y dime qué falla'] },
      { id: 'system', icon: I.system, name: 'Estado del equipo', short: 'CPU, GPU, RAM, disco y procesos', ...feature('system'),
        long: 'Te digo cómo va el PC: CPU, gráfica (uso, temperatura), memoria, disco, red y qué programas consumen más. El panel Sistema lo muestra con gráficos.',
        examples: ['¿Por qué va lento el PC?', '¿Cuánta RAM estoy usando?'] },
    ],
  },
  {
    name: 'Organización',
    items: [
      { id: 'reminders', icon: I.bell, name: 'Recordatorios y alarmas', short: 'Te aviso a la hora que digas', ...feature('reminders'),
        long: 'Recordatorios y alarmas por voz, también repetidos (cada día o de lunes a viernes). Te aviso con sonido, voz y notificación de Windows, aunque NEXUS esté cerrado.',
        examples: ['Avísame en 20 minutos de sacar la ropa', 'Pon una alarma a las 7 de lunes a viernes'] },
      { id: 'calendar', icon: I.calendar, name: 'Calendario', short: 'Tus citas de Google, Outlook o iCloud', ...feature('calendar'),
        long: 'Con tu calendario conectado (Ajustes → Cuentas) te digo qué tienes, lo incluyo en el resumen del día y te aviso 10 minutos antes de cada cita.',
        examples: ['¿Qué tengo mañana?'], more: ['accounts', 'Cuentas'] },
      { id: 'routines', icon: I.routines, name: 'Rutinas', short: 'Varias acciones con una frase o a una hora', ...feature('routines'),
        long: 'Guardas una lista de pasos y la lanzo con una frase, a una hora o con un botón. Se ven y se pausan en el panel Rutinas.',
        examples: ['Crea una rutina Modo trabajo que abra VS Code y ponga mi lista Focus'] },
      { id: 'briefing', icon: I.sun, name: 'Resumen de la mañana', short: 'Tiempo, citas, recordatorios y noticias', ...setting(S => !!S.briefing, app => app.flip('briefing')),
        long: 'La primera vez que me abres cada día te cuento el tiempo, tus citas y recordatorios y las noticias más interesantes, y te pregunto tus prioridades. También al decir «buenos días».',
        examples: ['Buenos días', '¿Qué tengo hoy?'] },
      { id: 'priorities', icon: I.target, name: 'Prioridades del día', short: 'Tus tres cosas importantes de hoy', ...feature('priorities'),
        long: 'Por la mañana te pregunto qué tres cosas quieres sacar hoy, y por la noche repasamos cuáles hiciste.',
        examples: ['Mis prioridades de hoy son el informe, el gimnasio y llamar a mamá', 'Ya he hecho el informe'] },
      { id: 'evening', icon: I.moon, name: 'Resumen de la noche', short: 'Qué hiciste y qué tienes mañana', ...setting(S => S.eveningReview !== false, app => app.flip('eveningReview')),
        long: 'A la hora que elijas te cuento qué hiciste, qué queda pendiente y qué tienes mañana. Si estás jugando o presentando, espero.',
        examples: ['Resumen de la noche'], more: ['system', 'Sistema'] },
      { id: 'proactive', icon: I.spark, name: 'Avisos por mi cuenta', short: 'Solo lo importante, pocos al día', ...setting(S => S.proactive !== false, app => app.flip('proactive')),
        long: 'Te aviso sin que preguntes solo si es útil: una cita en 10 minutos, el PC al límite, batería baja o disco casi lleno. Como mucho seis al día y nada de noche.',
        examples: [] },
    ],
  },
  {
    name: 'Información',
    items: [
      { id: 'web', icon: I.globe, name: 'Buscar en internet', short: 'Actualidad, precios y datos recientes', ...setting(S => !!(S.agent || {}).web, app => app.setAgent('web', 'agentWeb')),
        long: 'Busco en internet (DuckDuckGo, gratis) y leo páginas cuando hace falta un dato reciente: precios, resultados, horarios…',
        examples: ['¿Cuándo sale el próximo GTA?', '¿Cuánto cuesta una RTX 5070?'] },
      { id: 'research', icon: I.search, name: 'Investigación a fondo', short: 'Informe con fuentes citadas', ...feature('research'),
        long: 'Busco desde varios ángulos, leo las mejores fuentes y te doy un informe con citas numeradas y un apartado de lo que no está claro.',
        examples: ['Investiga a fondo qué portátil comprar por 1000 €'] },
      { id: 'news', icon: I.news, name: 'Noticias', short: 'Lo interesante del día, sin política', ...feature('news'),
        long: 'Panel con lo más reciente de tecnología, ciencia, curiosidades y lo que elijas, sin política. Te lo puedo leer en voz alta. Incluye «En un día como hoy».',
        examples: ['¿Qué noticias hay hoy?'] },
      { id: 'slides', icon: I.slides, name: 'Presentaciones', short: 'Creo un PowerPoint con diseño', ...feature('slides'),
        long: 'Escribo el contenido y creo un PowerPoint con los colores de tu tema en Documentos\\NEXUS\\Presentaciones, y lo abro.',
        examples: ['Hazme una presentación sobre el sistema solar'] },
    ],
  },
  {
    name: 'Seguridad y escritorio',
    items: [
      { id: 'activity', icon: I.undo, name: 'Actividad y deshacer', short: 'Todo lo que hago, con deshacer', always: true,
        long: 'El panel Actividad muestra cada cambio que hago en tu PC, con un botón para deshacerlo, y una pausa total que me impide cambiar nada. Siempre está activo por seguridad.',
        examples: ['Deshaz lo último'] },
      { id: 'private', icon: I.eye, name: 'Modo privado', short: 'El botón del ojo en la barra', always: true,
        long: 'Mientras está activo no guardo conversaciones, no aprendo nada y no miro la pantalla ni la cámara. Se enciende y apaga con el botón del ojo de la barra.',
        examples: [] },
      { id: 'wallpaper', icon: I.wallpaper, name: 'Fondo de escritorio', short: 'Vivo detrás de tus iconos', always: true,
        long: 'Me pongo como fondo de pantalla animado, detrás de los iconos, y me quedo quieto mientras usas otras apps. Se activa y ajusta en Sistema.',
        examples: [], more: ['system', 'Sistema'] },
    ],
  },
];

/** Panels of the dock that belong to a feature (hidden when it is off). */
export const DOCK_FEATURE = { music: 'music', news: 'news', routines: 'routines', system: 'system' };
